name: medusa-operator build

on:
  push:
    branches:
      - master

  pull_request:
    branches: [ master ]

jobs:
  build_operator_image:
    name: Build medusa-operator image
    runs-on: ubuntu-latest
    env:
      GOPATH: /home/runner/go
      GOROOT: /usr/local/go1.15
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Setup Protoc
        uses: arduino/setup-protoc@v1

      - name: Setup gRPC Go Plugins
        run: |
          export GO111MODULE=on
          go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run unit tests
        run: |
          export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
          make test
        shell: bash

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/master'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        if: github.ref == 'refs/heads/master'
        run: make docker-build docker-push